import * as THREE from 'three';
import { Game } from './core/Game.js';
import { MissionDirector } from './missions/MissionDirector.js';
const container=document.querySelector('#game');const game=new Game(container);game.missionAI=new MissionDirector(game);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(240,240),new THREE.MeshStandardMaterial({color:0x536b48,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;game.scene.add(ground);
function building(x,z,w,h,d,color=0xb7a78b){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,roughness:.78,metalness:.05}));m.position.set(x,h/2,z);m.castShadow=true;m.receiveShadow=true;game.scene.add(m);}
[[-12,-8,10,8,10,0xc6b58e],[5,-12,8,14,8,0x9eacb0],[15,4,12,7,10,0xd1c09b],[-18,12,9,11,12,0xa98f78],[3,15,14,5,8,0x8f9f83],[-38,-30,15,18,12,0xbca789],[42,-25,11,22,11,0x8d9da3],[35,30,18,9,15,0xc9b48f],[-42,35,13,16,13,0xa3a88c]].forEach(a=>building(...a));
const ui=()=>{const s=game.state.get();const set=(id,t)=>{const e=document.querySelector(id);if(e)e.textContent=t;};set('#money','RWF '+Math.floor(s.player.money).toLocaleString());set('#rep','REP '+s.player.reputation);set('#weather',s.world.weather.toUpperCase());set('#district',s.world.district.toUpperCase());set('#clock',String(Math.floor(s.world.time/60)%24).padStart(2,'0')+':'+String(s.world.time%60).padStart(2,'0'));if(s.mission)set('#mission','MISSION: '+s.mission.title+' · '+Math.round(s.mission.progress)+'%');set('#identity','IDENTITY: '+(s.identity?.label||'CITY EXPLORER'));};
game.state.subscribe(ui);setInterval(ui,250);game.events.on('mission:completed',e=>{const el=document.querySelector('#mission');if(el)el.textContent='MISSION COMPLETE +RWF '+e.reward;});game.events.on('mission:director',e=>{const el=document.querySelector('#mission');if(el)el.textContent='AI MISSION: '+e.mission.title;});game.events.on('vehicle:speed',e=>{const el=document.querySelector('#vehicle');if(el&&game.vehicles.active)el.textContent='DRIVING: '+game.vehicles.active.name+' · '+Math.round(e.speed)+' km/h';});game.events.on('vehicle:ability-active',d=>{const e=document.querySelector('#vehicle-ability');if(e)e.textContent=`ACTIVE: ${d.action.toUpperCase()} · ${d.vehicle}`;});
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k==='r')game.weather.setWeather(game.state.get().world.weather==='rain'?'clear':'rain');if(k==='t')game.weather.setWeather(game.state.get().world.weather==='storm'?'clear':'storm');if(k==='1')game.missions.start('first-run');if(k==='2')game.missions.start('night-drive');if(k==='3')game.missions.start('storm-chase');if(k==='4')game.missions.start('city-tour');if(k==='g'){const shop=game.world.getNearestShop(game.player.position);if(shop)game.nav.setTarget(shop.name);}if(k==='f'){if(game.socialEvents?.active)game.socialEvents.accept();else game.opportunities.commit();}if(k==='x'){if(game.socialEvents?.active)game.socialEvents.reject();else game.opportunities.reject();}if(k==='q')game.vehicleAbilities2?.trigger();});addEventListener('resize',()=>game.resize());addEventListener('beforeunload',()=>game.save());ui();game.start();
