const CLAMP=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const ROUTES=[['Kimironko','Remera',1.15],['Remera','Kacyiru',.9],['Kacyiru','Kimihurura',.8],['Kimihurura','KigaliCBD',1.05],['KigaliCBD','Nyamirambo',1.1],['Nyamirambo','Kimironko',.95],['KigaliCBD','Remera',1.2],['Kacyiru','Kimironko',.85],['Kimihurura','Remera',.9]];
const CARGO={food:{weight:1,value:80},parts:{weight:2,value:240},textiles:{weight:1.4,value:150},fuel:{weight:1.2,value:110},electronics:{weight:.8,value:360},services:{weight:.3,value:190},vehicles:{weight:8,value:900},recovery:{weight:3,value:280},supplies:{weight:2,value:210},permits:{weight:.2,value:300},delivery:{weight:1,value:130}};
const VEHICLE_CAPACITY={'Market Hauler':24,'Kigali Safari 4x4':16,'KGL Workhorse Pickup':20,'Kigali Shuttle Van':14,'Moto Taxi':5,'KGL E-Moto':4,'Kigali Runner':6};

export class CargoSupplyChainSystem{
 constructor(game){this.game=game;this.tick=0;this.orderTimer=0;const saved=game.state.get().cargoSupplyChain||{};this.state=saved.routes?{...saved}:this.empty();this.seed();this.bind();this.sync();}
 empty(){return{routes:{},cargo:{items:[],weight:0,capacity:6,vehicle:null},active:null,deliveries:[],incidents:[],network:{volume:0,pressure:0,activeRoutes:0},updatedAt:0};}
 seed(){for(const [from,to,base] of ROUTES){const id=from+'->'+to;if(!this.state.routes[id])this.state.routes[id]={id,from,to,base,pressure:.2,traffic:1,security:1,demand:1,supply:1,active:true,deliveries:0};}}
 bind(){this.game.events.on('vehicle:changed',v=>this.refreshCapacity(v));this.game.events.on('faction:economic-order',o=>this.attachOrder(o));this.game.events.on('faction:economic-order-resolved',e=>this.resolveOrder(e));this.game.events.on('faction:economy-purchase',e=>this.cargoSignal(e));this.game.events.on('faction:black-market-purchase',e=>this.riskSignal(e));this.game.events.on('district:trade-opportunity',e=>this.tradeSignal(e));this.game.events.on('police:alert',e=>this.securitySignal(e));this.game.events.on('world:consequence',e=>this.consequence(e));}
 refreshCapacity(v=this.game.vehicles.active){const name=v?.name;this.state.cargo.capacity=VEHICLE_CAPACITY[name]??6;this.state.cargo.vehicle=name||null;this.state.cargo.weight=this.weight();this.sync();}
 weight(){return this.state.cargo.items.reduce((s,i)=>s+(CARGO[i.good]?.weight||1)*(i.quantity||0),0);}
 addCargo(good,quantity=1,source=null,destination=null){if(!CARGO[good])return false;quantity=Math.max(1,Math.floor(quantity));const next=this.weight()+CARGO[good].weight*quantity;if(next>this.state.cargo.capacity)return false;const item=this.state.cargo.items.find(i=>i.good===good&&i.destination===destination);if(item)item.quantity+=quantity;else this.state.cargo.items.push({good,quantity,source,destination});this.state.cargo.weight=this.weight();this.sync();this.game.events.emit('cargo:loaded',{good,quantity,weight:this.state.cargo.weight,capacity:this.state.cargo.capacity});return true;}
 removeCargo(good,quantity=1){const item=this.state.cargo.items.find(i=>i.good===good);if(!item||item.quantity<quantity)return false;item.quantity-=quantity;if(item.quantity<=0)this.state.cargo.items=this.state.cargo.items.filter(x=>x!==item);this.state.cargo.weight=this.weight();this.sync();return true;}
 attachOrder(o){if(!o?.good)return;const route=Object.values(this.state.routes).find(r=>r.to===o.district)||Object.values(this.state.routes).find(r=>r.from===o.district);if(route)this.state.active={orderId:o.id,routeId:route.id,good:o.good,quantity:o.quantity,reward:o.reward,status:'ready'};this.sync();}
 loadOrder(orderId){const econ=this.game.factionEconomy;if(!econ)return false;const o=econ.state.orders.find(x=>x.id===orderId&&x.status==='available');if(!o)return false;if(!this.addCargo(o.good,o.quantity,o.faction,o.district))return false;o.status='loaded';const route=Object.values(this.state.routes).find(r=>r.to===o.district)||Object.values(this.state.routes).find(r=>r.from===o.district);this.state.active={orderId:o.id,routeId:route?.id||Object.keys(this.state.routes)[0],good:o.good,quantity:o.quantity,reward:o.reward,status:'loaded',from:route?.from||o.faction,to:route?.to||o.district};econ.sync();this.sync();this.game.events.emit('cargo:order-loaded',{...this.state.active,to:o.district});return true;}
 resolveOrder(e){if(!this.state.active||this.state.active.orderId!==e.id)return;this.state.active.status=e.success?'delivered':'failed';if(e.success){const item=this.state.cargo.items.find(i=>i.good===this.state.active.good&&i.destination===this.state.active.to);if(item){item.quantity=Math.max(0,item.quantity-this.state.active.quantity);if(item.quantity===0)this.state.cargo.items=this.state.cargo.items.filter(x=>x!==item);}this.state.cargo.weight=this.weight();this.state.deliveries.unshift({...this.state.active,at:Date.now()});}this.sync();}
 cargoSignal(e){if(e?.good)this.addCargo(e.good,Math.min(1,Number(e.quantity||1)),e.faction);}
 riskSignal(e){this.state.incidents.unshift({type:'black-market',risk:e.risk||0,at:Date.now()});this.state.incidents=this.state.incidents.slice(0,48);this.game.wanted.incident(Math.max(0,(e.risk||0)*.7));this.sync();}
 tradeSignal(e){const route=Object.values(this.state.routes).find(r=>r.from===e.from&&r.to===e.to)||Object.values(this.state.routes).find(r=>r.from===e.from);if(route){route.demand=CLAMP(route.demand+.08,.5,2);route.pressure=CLAMP(route.pressure+.06);}}
 securitySignal(e){for(const r of Object.values(this.state.routes))r.security=CLAMP(r.security-(Number(e.level||1)*.025));}
 consequence(e){const d=e.district;for(const r of Object.values(this.state.routes))if(r.from===d||r.to===d)r.pressure=CLAMP(r.pressure+Number(e.heat||0)*.08);}
 update(dt){this.tick+=dt;this.orderTimer+=dt;if(this.tick<2)return;const step=this.tick;this.tick=0;const vehicle=this.game.vehicles.active;this.refreshCapacity(vehicle);const speed=Math.abs(vehicle?.speed||0);for(const r of Object.values(this.state.routes)){const load=this.state.cargo.weight/Math.max(1,this.state.cargo.capacity);r.traffic=CLAMP(1+r.pressure*.7+load*.25,.5,2);r.pressure=CLAMP(r.pressure+(r.demand-r.supply)*.015*step+Math.max(0,load-.6)*.01*step);r.supply=CLAMP(r.supply+.012*step-r.demand*.006*step,.5,2);r.demand=CLAMP(r.demand-.008*step,.5,2);if(speed>18)r.pressure=CLAMP(r.pressure+.004*step);r.security=CLAMP(r.security*.995+(1-r.security)*.003);if(r.pressure>.7&&r.active)this.game.events.emit('cargo:route-pressure',{route:r.id,pressure:r.pressure,traffic:r.traffic});}if(this.orderTimer>8){this.orderTimer=0;this.generateRouteOpportunity();}const vals=Object.values(this.state.routes);this.state.network={volume:vals.reduce((s,r)=>s+r.base*r.demand,0),pressure:vals.reduce((s,r)=>s+r.pressure,0)/vals.length,activeRoutes:vals.filter(r=>r.pressure>.3).length};this.state.updatedAt=Date.now();this.sync();}
 generateRouteOpportunity(){const hot=Object.values(this.state.routes).sort((a,b)=>b.pressure-a.pressure)[0];if(!hot||hot.pressure<.45)return;const good=['food','parts','fuel','textiles'][Math.floor(hot.pressure*10)%4];const reward=Math.round((CARGO[good]?.value||100)*(1.5+hot.pressure));this.game.events.emit('cargo:route-opportunity',{route:hot.id,from:hot.from,to:hot.to,good,reward,risk:CLAMP(hot.pressure*.55),distance:Math.round(8+hot.base*12)});}
 cargoManifest(){return{...this.state.cargo,items:this.state.cargo.items.map(x=>({...x}))};}
 sync(){this.game.state.update({cargoSupplyChain:this.state});}
}