const TYPES={
 traffic:{weight:1.1},economy:{weight:1.25},social:{weight:1.05},safety:{weight:1.3},weather:{weight:1.15},information:{weight:.9}
};
const CLAMP=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
export class CityEventCascadeSystem{
 constructor(game,ecosystem,districtAI,districtEvolution){this.game=game;this.ecosystem=ecosystem;this.ai=districtAI;this.evolution=districtEvolution;this.tick=0;this.nextId=1;this.active=[];const saved=game.state.get().cityEventCascade||{};this.state=saved.events?{...saved}:this.empty();this.bind();this.sync();}
 empty(){return{events:[],districts:{},networkPressure:0,cascadeCount:0,lastEvent:0};}
 bind(){this.game.events.on('district:shock',e=>this.seed('shock',e));this.game.events.on('district:trade-opportunity',e=>this.seed('trade',e));this.game.events.on('city:activity-signal',e=>this.seed('activity',e));this.game.events.on('world:consequence',e=>this.seed('consequence',e));this.game.events.on('weather:changed',e=>this.seed('weather',e));}
 seed(type,data={}){const district=data.district||data.from||this.game.state.get().world?.district||'default';const spec=TYPES[type==='trade'?'economy':type]||TYPES.information;const intensity=CLAMP(Number(data.pressure||data.intensity||data.heat||.35)*spec.weight,.08,1);const event={id:this.nextId++,type,district,intensity,createdAt:Date.now(),ttl:18,stage:0,visited:{[district]:true}};this.active.push(event);this.state.events.push(event);this.state.cascadeCount++;this.state.lastEvent=Date.now();this.propagate(event);this.sync();this.game.events.emit('city:cascade-start',{id:event.id,type,district,intensity});}
 propagate(event){const edges=this.ecosystem?.state?.edges||[];for(const edge of edges.filter(e=>e.from===event.district||e.to===event.district)){const target=edge.from===event.district?edge.to:edge.from;if(event.visited[target])continue;const flow=Math.min(1,(edge.total||1)/12),strength=CLAMP(event.intensity*(.35+flow*.65),.04,.92);if(strength<.16)continue;event.visited[target]=true;event.stage++;const node=this.state.districts[target]||(this.state.districts[target]={traffic:0,economy:0,social:0,safety:0,weather:0,information:0,pressure:0});const key=event.type==='trade'?'economy':event.type==='activity'?'social':event.type==='shock'?'safety':event.type;node[key]=CLAMP((node[key]||0)+strength);node.pressure=CLAMP(node.pressure+strength*.45);this.game.events.emit('city:cascade-wave',{id:event.id,type:event.type,from:event.district,to:target,strength});}}
 applyNode(name,node,dt){const pressure=node.pressure||0;if(pressure>.55)this.game.events.emit('city:cascade-pressure',{district:name,pressure});if(this.game.state.get().world?.district===name&&pressure>.7)this.game.events.emit('city:cascade-player-signal',{district:name,pressure,signals:{...node}});const decay=Math.pow(.86,dt);for(const k of ['traffic','economy','social','safety','weather','information'])node[k]*=decay;node.pressure*=Math.pow(.9,dt);}
 update(dt){this.tick+=dt;if(this.tick<1)return;const step=this.tick;this.tick=0;for(const e of this.active)e.ttl-=step;for(const e of this.active){if(e.ttl>0&&e.stage<4&&e.intensity>.2)this.propagate(e);}this.active=this.active.filter(e=>e.ttl>0&&e.intensity>.06);for(const [name,node] of Object.entries(this.state.districts))this.applyNode(name,node,step);const p=Object.values(this.state.districts).map(n=>n.pressure||0);this.state.networkPressure=p.length?p.reduce((a,b)=>a+b,0)/p.length:0;this.state.events=this.state.events.slice(-32);this.sync();if(this.state.networkPressure>.62)this.game.events.emit('city:cascade-network-alert',{pressure:this.state.networkPressure});}
 sync(){this.game.state.update({cityEventCascade:this.state});}
}
