const CLAMP=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const ACTIONS={recruit:{trust:.08,rep:2,reward:180},delivery:{trust:.04,rep:1,reward:260},protection:{trust:.1,rep:3,reward:420},recovery:{trust:.06,rep:2,reward:320},sabotage:{trust:-.12,rep:-2,reward:520}};
export class FactionGameplaySystem{
 constructor(game){this.game=game;this.tick=0;this.nextId=1;const saved=game.state.get().factionGameplay||{};this.state=saved.factions?{...saved}:this.empty();this.bind();this.sync();}
 empty(){return{factions:{},missions:[],active:[],player:{trust:{},influence:{},heat:{}},updatedAt:0};}
 bind(){this.game.events.on('npc:faction-joined',e=>this.ensure(e.faction));this.game.events.on('npc:faction-left',e=>this.heat(e.faction,.02));this.game.events.on('npc:relationship-network',()=>this.refresh());this.game.events.on('district:trade-opportunity',e=>this.opportunity(e));this.game.events.on('world:consequence',e=>this.consequence(e));}
 ensure(name){if(!name)return null;return this.state.factions[name]||(this.state.factions[name]={name,trust:.35,influence:0,heat:0,resources:500,missions:0,completed:0,failed:0,safeSpots:0});}
 heat(name,value){const f=this.ensure(name);if(f)f.heat=CLAMP(f.heat+value);}
 opportunity(e={}){const district=e.from||e.district;for(const name of Object.keys(this.state.factions)){const f=this.ensure(name);if(f.resources>50&&f.heat<.8)this.generate(name,'delivery',district);}}
 generate(faction,action='delivery',district='default'){const f=this.ensure(faction),spec=ACTIONS[action]||ACTIONS.delivery;if(!f)return null;const m={id:this.nextId++,faction,action,district,reward:spec.reward+Math.round(f.influence*180),trust:spec.trust,rep:spec.rep,expires:Date.now()+90000,status:'available'};this.state.missions.push(m);this.state.missions=this.state.missions.slice(-32);this.game.events.emit('faction:mission-generated',m);this.sync();return m;}
 accept(id){const m=this.state.missions.find(x=>x.id===id&&x.status==='available');if(!m)return false;m.status='active';this.state.active.push(m.id);this.ensure(m.faction).missions++;this.game.events.emit('faction:mission-accepted',m);this.sync();return true;}
 resolve(id,success=true){const m=this.state.missions.find(x=>x.id===id&&x.status==='active');if(!m)return false;const f=this.ensure(m.faction),spec=ACTIONS[m.action]||ACTIONS.delivery;m.status=success?'completed':'failed';f.resources+=success?spec.reward*.18:-100;f.completed+=success?1:0;f.failed+=success?0:1;f.trust=CLAMP(f.trust+(success?spec.trust:-Math.abs(spec.trust)*1.5));f.influence=CLAMP(f.influence+(success?.035:-.025));this.state.player.trust[m.faction]=f.trust;this.state.player.influence[m.faction]=f.influence;this.state.player.heat[m.faction]=f.heat;this.state.active=this.state.active.filter(x=>x!==id);this.game.events.emit('faction:mission-resolved',{...m,success,trust:f.trust,influence:f.influence});this.sync();return true;}
 recruit(faction){return this.generate(faction,'recruit');}
 safeSpot(faction){const f=this.ensure(faction);if(!f)return false;f.safeSpots++;f.influence=CLAMP(f.influence+.04);this.game.events.emit('faction:safe-spot',{faction,safeSpots:f.safeSpots});this.sync();return true;}
 consequence(e={}){for(const f of Object.values(this.state.factions))if(f.heat<.65)f.resources=Math.max(0,f.resources-Number(e.reward||0)*.002);}
 refresh(){for(const f of Object.values(this.state.factions)){f.influence=CLAMP(f.influence+(f.completed*.002)-(f.failed*.003));f.trust=CLAMP(f.trust-f.heat*.002);}}
 update(dt){this.tick+=dt;if(this.tick<5)return;const step=this.tick;this.tick=0;const now=Date.now();for(const f of Object.values(this.state.factions)){f.resources=Math.min(5000,f.resources+step*1.5);f.heat*=Math.pow(.96,step);if(f.trust>.65&&f.influence>.35&&Math.random()<.25)this.generate(f.name,'protection');}for(const m of this.state.missions)if(m.status==='available'&&m.expires<now)m.status='expired';this.state.missions=this.state.missions.filter(m=>m.status!=='expired'||m.id>this.nextId-12);this.state.updatedAt=now;this.sync();}
 sync(){this.game.state.update({factionGameplay:this.state});}
}
