const CLAMP=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const GOODS=['food','parts','fuel','textiles','electronics','supplies','recovery'];
export class LogisticsAISystem{
constructor(game){this.game=game;this.tick=0;this.orderTimer=0;const saved=game.state.get().logisticsAI||{};this.state=saved.routes?{...saved}:this.empty();this.bind();this.sync();}
empty(){return{routes:{},activeSignals:[],playerProfile:{risk:0,reliability:0,volume:0},updatedAt:0};}
bind(){this.game.events.on('cargo:delivery-started',e=>this.start(e));this.game.events.on('cargo:delivery-arrived',e=>this.finish(e,true));this.game.events.on('cargo:delivery-failed',e=>this.finish(e,false));this.game.events.on('cargo:route-pressure',e=>this.pressure(e));this.game.events.on('world:consequence',e=>this.consequence(e));this.game.events.on('faction:conflict-event',e=>this.conflict(e));}
ensure(id,data={}){if(!id)return null;if(!this.state.routes[id])this.state.routes[id]={id,score:.5,risk:.2,rewardBias:1,trafficBias:1,confidence:.5,attempts:0,successes:0};Object.assign(this.state.routes[id],data);return this.state.routes[id];}
profile(){const h=this.game.state.get().physicalDelivery?.history||[];const attempts=h.length,successes=h.filter(x=>x.status==='delivered').length;const fast=h.filter(x=>x.etaSeconds!=null&&x.etaSeconds<90).length;const risk=h.reduce((s,x)=>s+(x.risk||0),0);return{risk:CLAMP(risk/Math.max(1,attempts)),reliability:attempts?successes/attempts:0,volume:attempts,fast:attempts?fast/attempts:0};}
start(e){const id=e.routeId||((e.from||'Kigali')+'->'+e.to);this.ensure(id).attempts++;}
finish(e,success){const a=this.game.state.get().physicalDelivery?.active;const id=a?.routeId||((e.from||'Kigali')+'->'+(e.district||'Kigali'));const r=this.ensure(id);if(success){r.successes++;r.confidence=CLAMP(r.confidence+.06);r.rewardBias=CLAMP(r.rewardBias-.01,.8,1.35);}else{r.risk=CLAMP(r.risk+.08);r.rewardBias=CLAMP(r.rewardBias+.04,.8,1.35);}}
pressure(e={}){const r=this.ensure(e.route);r.risk=CLAMP(r.risk+Number(e.pressure||0)*.05);r.score=CLAMP(.55-r.risk*.45+Number(e.traffic||1)*.05);}
consequence(e={}){for(const r of Object.values(this.state.routes))r.risk=CLAMP(r.risk+Number(e.heat||0)*.025);}
conflict(e={}){const d=e.district;const routes=this.game.cargoSupplyChain?.state?.routes||{};for(const r of Object.values(routes))if(r.from===d||r.to===d)this.ensure(r.id).risk=CLAMP(this.ensure(r.id).risk+.08);}
scoreRoute(route,player){const r=this.ensure(route.id),f=this.game.factionEconomy?.state?.factions||{};const faction=Object.values(f).find(x=>x.district===route.to||x.district===route.from);const demand=Number(faction?.demand||1),security=Number(route.security||1);const reward=(1+(demand-1)*.5)*r.rewardBias;const risk=(r.risk+Math.max(0,1-security))*.55+route.pressure*.3;return{route,score:reward-risk*1.2+player.reliability*.18,rewardBias:r.rewardBias,risk};}
generate(){const cargo=this.game.cargoSupplyChain?.state?.routes||{};const player=this.state.playerProfile;const ranked=Object.values(cargo).map(r=>this.scoreRoute(r,player)).sort((a,b)=>b.score-a.score);const pick=ranked[0];if(!pick)return;const route=pick.route;const good=GOODS[Math.floor((route.demand*100+route.pressure*10)%GOODS.length)];const base=route.base||1;const value={food:80,parts:240,fuel:110,textiles:150,electronics:360,supplies:210,recovery:280}[good]||100;const reward=Math.round(value*(1.45+route.demand*.55)*pick.rewardBias);const signal={route:route.id,from:route.from,to:route.to,good,reward,risk:CLAMP(pick.risk),distance:Math.round(8+base*12),reason:pick.risk>.55?'HIGH RISK / HIGH VALUE':'AI ROUTE MATCH',generatedAt:Date.now()};this.state.activeSignals.unshift(signal);this.state.activeSignals=this.state.activeSignals.slice(0,12);this.game.events.emit('logistics:ai-opportunity',signal);}
update(dt){this.tick+=dt;this.orderTimer+=dt;if(this.tick<3)return;const step=this.tick;this.tick=0;this.state.playerProfile=this.profile();for(const r of Object.values(this.state.routes)){r.confidence*=Math.pow(.997,step);r.risk*=Math.pow(.985,step);r.score=CLAMP(r.score*.99+.5*.01);}if(this.orderTimer>10){this.orderTimer=0;this.generate();}this.state.updatedAt=Date.now();this.sync();}
sync(){this.game.state.update({logisticsAI:this.state});}
}