export class RoadGraph{
  constructor(){this.nodes=new Map();this.edges=new Map();}
  key(x,z){return `${Math.round(x)}:${Math.round(z)}`;}
  addRoad(road,project){const lines=road.geometry.type==='LineString'?[road.geometry.coordinates]:road.geometry.coordinates.flat();for(const line of lines){let prev=null;for(const c of line){const p=project(c[0],c[1]);const id=this.key(p.x,p.z);if(!this.nodes.has(id))this.nodes.set(id,{id,x:p.x,z:p.z,roads:new Set()});this.nodes.get(id).roads.add(road.id);if(prev&&prev!==id){const k=prev<id?`${prev}|${id}`:`${id}|${prev}`;this.edges.set(k,{a:prev,b:id,roadId:road.id,speed:road.speed,class:road.class});}prev=id;}}}
  build(roads,project){this.nodes.clear();this.edges.clear();for(const r of roads)this.addRoad(r,project);return {nodes:this.nodes.size,edges:this.edges.size};}
  nearest(x,z){let best=null,d=Infinity;for(const n of this.nodes.values()){const q=(n.x-x)**2+(n.z-z)**2;if(q<d){d=q;best=n;}}return best;}
  neighbors(node){const out=[];for(const e of this.edges.values()){if(e.a===node.id)out.push(this.nodes.get(e.b));else if(e.b===node.id)out.push(this.nodes.get(e.a));}return out.filter(Boolean);}
  findPath(start,target){if(!start||!target)return[];if(start.id===target.id)return[start];const open=[{node:start,g:0,f:0,prev:null}],best=new Map([[start.id,0]]),closed=new Set();while(open.length){open.sort((a,b)=>a.f-b.f);const cur=open.shift();if(closed.has(cur.node.id))continue;closed.add(cur.node.id);if(cur.node.id===target.id){const path=[];let q=cur;while(q){path.unshift(q.node);q=q.prev;}return path;}for(const next of this.neighbors(cur.node)){if(closed.has(next.id))continue;const g=cur.g+Math.hypot(next.x-cur.node.x,next.z-cur.node.z);if(g>=(best.get(next.id)??Infinity))continue;best.set(next.id,g);const h=Math.hypot(target.x-next.x,target.z-next.z);open.push({node:next,g,f:g+h,prev:cur});}}return[];}
}
