import * as THREE from 'three';
export class GarageUI {
  constructor(game){this.game=game;this.open=false;this.el=null;this.preview=null;this.previewVehicle=null;this.dragging=false;this.lastX=0;this.autoRotate=true;this.zoom=5.6;this.lights=true;addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k==='b')this.toggle();if(k==='escape'&&this.open)this.toggle();});}
  toggle(){this.open=!this.open;this.render();if(this.open)this.syncPreview();}
  select(name){if(this.game.vehicles.selectVehicle(name)){this.render();this.syncPreview();}}
  buy(type,value){if(this.game.customization?.apply(type,value)){this.render();this.syncPreview();}}
  setupPreview(){if(this.preview)return;const host=this.el.querySelector('[data-preview]');if(!host)return;const canvas=document.createElement('canvas');canvas.className='garage-preview-canvas';host.appendChild(canvas);const scene=new THREE.Scene();scene.background=new THREE.Color(0x080c12);const camera=new THREE.PerspectiveCamera(35,1,.1,100);camera.position.set(0,1.7,this.zoom);camera.lookAt(0,.8,0);const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;const hemi=new THREE.HemisphereLight(0xffffff,0x24313c,2.4);scene.add(hemi);const key=new THREE.DirectionalLight(0xffffff,3);key.position.set(4,6,5);key.castShadow=true;scene.add(key);const rim=new THREE.DirectionalLight(0x8fb8ff,2);rim.position.set(-5,3,-4);scene.add(rim);const floor=new THREE.Mesh(new THREE.CylinderGeometry(4.2,4.2,.12,64),new THREE.MeshStandardMaterial({color:0x151b22,metalness:.45,roughness:.35}));floor.position.y=-.08;floor.receiveShadow=true;scene.add(floor);const ring=new THREE.Mesh(new THREE.TorusGeometry(3.2,.025,8,96),new THREE.MeshBasicMaterial({color:0x71869a,transparent:true,opacity:.45}));ring.rotation.x=Math.PI/2;ring.position.y=.01;scene.add(ring);this.preview={scene,camera,renderer,hemi,key,rim,floor,ring};this.resizePreview();canvas.addEventListener('pointerdown',e=>{this.dragging=true;this.lastX=e.clientX;canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!this.dragging||!this.previewVehicle)return;this.previewVehicle.rotation.y+=(e.clientX-this.lastX)*.012;this.lastX=e.clientX;this.autoRotate=false;});canvas.addEventListener('pointerup',()=>this.dragging=false);canvas.addEventListener('pointerleave',()=>this.dragging=false);}
  resizePreview(){if(!this.preview||!this.el)return;const canvas=this.preview.renderer.domElement;const w=Math.max(240,canvas.parentElement.clientWidth||600),h=Math.max(260,canvas.parentElement.clientHeight||420);this.preview.renderer.setSize(w,h,false);this.preview.camera.aspect=w/h;this.preview.camera.updateProjectionMatrix();}
  syncPreview(){if(!this.open)return;this.setupPreview();if(!this.preview)return;const v=this.game.vehicles.active;if(!v)return;if(this.previewVehicle)this.preview.scene.remove(this.previewVehicle);this.previewVehicle=v.mesh.clone(true);this.previewVehicle.traverse(o=>{if(o.material){o.material=o.material.clone();}o.castShadow=true;o.receiveShadow=true;});this.previewVehicle.position.set(0,0,0);this.previewVehicle.rotation.y=Math.PI;this.previewVehicle.scale.setScalar(1.05);this.preview.scene.add(this.previewVehicle);this.preview.camera.position.z=this.zoom;this.preview.camera.lookAt(0,.8,0);}
  tool(action){if(action==='reset'){this.autoRotate=true;if(this.previewVehicle)this.previewVehicle.rotation.y=Math.PI;}if(action==='rotate')this.autoRotate=!this.autoRotate;if(action==='zoomIn')this.zoom=Math.max(3.8,this.zoom-.5);if(action==='zoomOut')this.zoom=Math.min(8,this.zoom+.5);if(action==='lights')this.lights=!this.lights;if(this.preview){this.preview.camera.position.z=this.zoom;this.preview.hemi.intensity=this.lights?2.4:.45;this.preview.key.intensity=this.lights?3:.7;this.preview.rim.intensity=this.lights?2:.3;} }
  repair(){if(this.game.customization?.repair())this.render();}
  render(){
    if(!this.el){this.el=document.createElement('div');this.el.id='garage-panel';document.body.appendChild(this.el);}
    if(!this.open){this.el.innerHTML='';this.el.className='hidden';return;}
    this.el.className='garage-panel';const v=this.game.vehicles.active;const money=this.game.state.get().player.money;
    const cards=this.game.vehicles.vehicles.map(car=>`<button class="vehicle-card ${car===v?'selected':''}" data-select="${car.name}"><strong>${car.name}</strong><span>${Math.round(car.maxSpeed)} TOP · ${Math.round((car.grip||.92)*100)} GRIP</span></button>`).join('');
    if(!v){this.el.innerHTML=`<div class="garage-card"><div class="garage-head"><div><small>KIGALI MOTORS · SHOWROOM</small><h2>SELECT VEHICLE</h2></div><button data-close>×</button></div><div class="vehicle-list">${cards}</div></div>`;this.bind();return;}
    const stat=(label,value)=>`<div class="gstat"><span>${label}</span><strong>${value}</strong></div>`;
    this.el.innerHTML=`<div class="garage-card garage-wide"><div class="garage-head"><div><small>KIGALI MOTORS · DIGITAL SHOWROOM</small><h2>${v.name}</h2></div><button data-close>×</button></div><div class="garage-layout"><div class="preview-wrap"><div data-preview></div><div class="preview-tools"><button data-tool="reset">RESET</button><button data-tool="rotate">AUTO ROTATE</button><button data-tool="zoomOut">−</button><button data-tool="zoomIn">+</button><button data-tool="lights">LIGHTS</button></div><div class="preview-hint">DRAG TO ROTATE · WHEEL / TOOLS TO ZOOM</div></div><div class="garage-controls"><div class="vehicle-list">${cards}</div><div class="garage-stats">${stat('HP',Math.round(v.health))}${stat('TOP SPEED',Math.round(v.maxSpeed))}${stat('GRIP',Math.round((v.grip||.92)*100)+'%')}${stat('FUEL',Math.round(v.fuel)+'%')}${stat('ENGINE',v.engineLevel||0)}${stat('BRAKES',v.brakeLevel||0)}${stat('SUSPENSION',v.suspensionLevel||0)}${stat('CASH','RWF '+Math.floor(money).toLocaleString())}</div><div class="garage-section"><h3>BODY & COLOR</h3>${['red','blue','black','white','gold'].map(x=>`<button data-paint="${x}">${x.toUpperCase()} · RWF 120</button>`).join('')}</div><div class="garage-section"><h3>WHEELS</h3>${['stock','sport','offroad'].map(x=>`<button data-wheel="${x}">${x.toUpperCase()} · RWF 180</button>`).join('')}</div><div class="garage-section"><h3>PERFORMANCE</h3><button data-buy="tires">TIRES · RWF 160</button><button data-buy="engine">ENGINE · RWF 420</button><button data-buy="brakes">BRAKES · RWF 260</button><button data-buy="suspension">SUSPENSION · RWF 300</button></div><div class="garage-section garage-actions"><button data-repair>REPAIR VEHICLE</button><button data-close>EXIT GARAGE</button></div></div></div></div>`;
    this.bind();this.setupPreview();this.syncPreview();
  }
  bind(){this.el.querySelector('[data-close]')?.addEventListener('click',()=>this.toggle());this.el.querySelectorAll('[data-select]').forEach(b=>b.addEventListener('click',()=>this.select(b.dataset.select)));this.el.querySelectorAll('[data-paint]').forEach(b=>b.addEventListener('click',()=>this.buy('paint',b.dataset.paint)));this.el.querySelectorAll('[data-wheel]').forEach(b=>b.addEventListener('click',()=>this.buy('wheels',b.dataset.wheel)));this.el.querySelectorAll('[data-buy]').forEach(b=>b.addEventListener('click',()=>this.buy(b.dataset.buy)));this.el.querySelectorAll('[data-tool]').forEach(b=>b.addEventListener('click',()=>this.tool(b.dataset.tool)));this.el.querySelector('[data-repair]')?.addEventListener('click',()=>this.repair());}
  update(){if(!this.open)return;if(this.preview){if(this.autoRotate&&this.previewVehicle)this.previewVehicle.rotation.y+=.004;this.preview.renderer.render(this.preview.scene,this.preview.camera);}}
}
