import * as THREE from 'three';
export class TrafficSystem {
  constructor(game){this.game=game;this.cars=[];this.lights=[];this.aiTimer=0;this.congestion=0;this.zoneCenters={CBD:[0,0],KIMIRONKO:[-32,0],REMERA:[32,0],KACYIRU:[0,32],NYARUTARAMA:[32,32],NYAMIRAMBO:[-32,-32],KICUKIRO:[-32,32],KANOMBE:[64,-32]};this.districtFlow={CBD:1,KIMIRONKO:1,REMERA:1,KACYIRU:1,NYARUTARAMA:.8,NYAMIRAMBO:1.15,KICUKIRO:1,KANOMBE:.8};this.bindAI();this.spawnTraffic();this.buildSignals();this.buildCrossings();}
  bindAI(){this.game.events.on('population:director',d=>{for(const [zone,data] of Object.entries(d.zones||{}))this.districtFlow[zone]=THREE.MathUtils.clamp(.65+(data.pressure||1)*.48,.65,1.8);});this.game.events.on('city:event',e=>{this.activeEvent=e;this.aiTimer=0;});}
  nearestZone(x,z){let best='CBD',dist=Infinity;for(const [zone,p] of Object.entries(this.zoneCenters)){const d=Math.hypot(x-p[0],z-p[1]);if(d<dist){dist=d;best=zone;}}return best;}
  spawnTraffic(){for(let i=0;i<28;i++)this.spawn(i);}
  spawn(i){const isMoto=i%5===0,isBus=i%11===0,g=new THREE.Group(),colors=[0xd13a32,0x2d5fa4,0xf0c33c,0xeeeeee,0x20252a,0x4d9b73];const body=new THREE.Mesh(new THREE.BoxGeometry(isBus?2.2:isMoto?.7:1.7,isBus?1.15:isMoto?.8:.5,isBus?6.2:isMoto?1.7:3.4),new THREE.MeshStandardMaterial({color:colors[i%colors.length],metalness:.35,roughness:.35}));body.position.y=isBus?.95:isMoto?.7:.55;body.castShadow=true;g.add(body);if(!isMoto){const cabin=new THREE.Mesh(new THREE.BoxGeometry(isBus?1.8:1.35,isBus?1:.48,isBus?3.4:1.5),new THREE.MeshStandardMaterial({color:0x17222c,roughness:.2,transparent:true,opacity:.9}));cabin.position.y=isBus?1.7:1.02;g.add(cabin);}if(isMoto){const rider=new THREE.Mesh(new THREE.SphereGeometry(.22,10,10),new THREE.MeshStandardMaterial({color:0x242b32}));rider.position.y=1.15;g.add(rider);}const lane=Math.floor(i/2)%7,horizontal=i%4>=2,road=-96+lane*32,dir=i%2?1:-1;if(horizontal){g.position.set(-110,0,road+(i%2?2:-2));g.rotation.y=dir>0?Math.PI/2:-Math.PI/2;}else{g.position.set(road+(i%2?2:-2),0,-110);g.rotation.y=dir>0?0:Math.PI;}this.game.scene.add(g);this.cars.push({mesh:g,speed:isBus?4.2:isMoto?8:5+(i%5)*1.7,baseSpeed:isBus?4.2:isMoto?8:5+(i%5)*1.7,axis:horizontal?'x':'z',dir,lane,kind:isBus?'bus':isMoto?'moto':'car',directedSpeed:0});}
  buildSignals(){for(let x=-96;x<=96;x+=32)for(let z=-96;z<=96;z+=32){const pole=new THREE.Mesh(new THREE.CylinderGeometry(.06,.08,2.7,8),new THREE.MeshStandardMaterial({color:0x303438,metalness:.5}));pole.position.set(x+5,1.35,z+5);this.game.scene.add(pole);const light=new THREE.Mesh(new THREE.BoxGeometry(.35,.7,.22),new THREE.MeshStandardMaterial({color:0x241c18,emissive:0x180d08}));light.position.set(x+5,2.65,z+5);this.game.scene.add(light);this.lights.push({mesh:light,phase:Math.random()*8,green:Math.random()>.5});}}
  buildCrossings(){for(let x=-96;x<=96;x+=32)for(let z=-96;z<=96;z+=32){const mat=new THREE.MeshBasicMaterial({color:0xf2ead7});for(let n=-2;n<=2;n++){const a=new THREE.Mesh(new THREE.PlaneGeometry(1.1,8),mat);a.rotation.x=-Math.PI/2;a.position.set(x+n*1.7,.045,z+6);this.game.scene.add(a);const b=new THREE.Mesh(new THREE.PlaneGeometry(8,1.1),mat);b.rotation.x=-Math.PI/2;b.position.set(x+6,.045,z+n*1.7);this.game.scene.add(b);}}}
  update(dt){for(const s of this.lights){s.phase=(s.phase+dt)%8;s.green=s.phase>2&&s.phase<6;const m=s.mesh.material;m.emissive.setHex(s.green?0x173b20:0x3b110c);m.color.setHex(s.green?0x347c46:0x7e3322);}let slow=0;const h=Math.floor(this.game.state.get().world.time/60)%24,rush=(h>=7&&h<9)||(h>=16&&h<19);for(const car of this.cars){const p=car.mesh.position,junction=car.axis==='x'?Math.abs(Math.round(p.x/32)*32-p.x)<1.8:Math.abs(Math.round(p.z/32)*32-p.z)<1.8;let target=car.baseSpeed/(this.districtFlow[this.nearestZone(p.x,p.z)]||1);if(rush)target*=.85;if(car.kind==='bus')target*=.78;if(car.kind==='moto')target*=1.12;if(this.activeEvent){const d=Math.hypot(p.x-this.activeEvent.x,p.z-this.activeEvent.z);if(d<28){if(this.activeEvent.type==='TRAFFIC SURGE'||this.activeEvent.type==='MARKET BUSY')target*=.62;if(this.activeEvent.type==='ROAD INCIDENT')target*=.38;if(this.activeEvent.type==='CROWD EVENT')target*=.7;}}const lightSlow=junction&&!this.isGreenFor(car);if(lightSlow)target=0;car.directedSpeed=THREE.MathUtils.clamp(target,car.kind==='moto'?3:2,car.baseSpeed*(rush?1.05:1));car.speed=THREE.MathUtils.lerp(car.speed,car.directedSpeed,dt*(lightSlow?5:2.4));if(car.speed<car.baseSpeed*.65)slow++;if(car.axis==='z')p.z+=car.speed*car.dir*dt;else p.x+=car.speed*car.dir*dt;if(p.x>112)p.x=-112;if(p.x<-112)p.x=112;if(p.z>112)p.z=-112;if(p.z<-112)p.z=112;}this.aiTimer+=dt;if(this.aiTimer>1){this.aiTimer=0;this.congestion=Math.round(slow/this.cars.length*100);const el=document.querySelector('#traffic-ai');if(el)el.textContent=`TRAFFIC AI: ${this.congestion}% CONGESTION · ${this.cars.length} VEHICLES`;this.game.events.emit('traffic:director',{congestion:this.congestion,vehicles:this.cars.length});}}
  isGreenFor(car){const key=Math.round((car.axis==='x'?car.mesh.position.z:car.mesh.position.x)/32);return ((key%2)+2)%2===0;}
}
