import * as THREE from 'three';
export class VehicleSystem {
  constructor(game){this.game=game;this.vehicles=[];this.active=null;this.keys=new Set();this.eHeld=false;addEventListener('keydown',e=>this.keys.add(e.key.toLowerCase()));addEventListener('keyup',e=>this.keys.delete(e.key.toLowerCase()));this.spawn('Kigali Runner',8,0,0xc52d2d,22);this.spawn('Moto Taxi',-8,5,0xf0c22b,16);this.loadUpgrades();}
  spawn(name,x,z,color,maxSpeed){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(2.4,.65,4.4),new THREE.MeshStandardMaterial({color,metalness:.45,roughness:.28}));body.position.y=.75;body.castShadow=true;g.add(body);const cabin=new THREE.Mesh(new THREE.BoxGeometry(1.9,.62,1.8),new THREE.MeshStandardMaterial({color:0x15202a,metalness:.2,roughness:.15,transparent:true,opacity:.92}));cabin.position.set(0,1.2,-.15);g.add(cabin);const wheels=[];for(const sx of[-1,1])for(const sz of[-1,1]){const wheel=new THREE.Mesh(new THREE.CylinderGeometry(.38,.38,.24,16),new THREE.MeshStandardMaterial({color:0x111111,roughness:.9}));wheel.rotation.z=Math.PI/2;wheel.position.set(sx*1.08,.42,sz*1.45);wheel.castShadow=true;g.add(wheel);wheels.push(wheel);}const lights=[];for(const x of[-.68,.68]){const head=new THREE.Mesh(new THREE.BoxGeometry(.28,.12,.08),new THREE.MeshStandardMaterial({color:0xfff1b0,emissive:0xffcc66,emissiveIntensity:1}));head.position.set(x,.86,-2.22);g.add(head);lights.push(head);const brake=new THREE.Mesh(new THREE.BoxGeometry(.3,.12,.08),new THREE.MeshStandardMaterial({color:0x440000,emissive:0x220000}));brake.position.set(x,.86,2.22);g.add(brake);lights.push(brake);}const exhaust=new THREE.Mesh(new THREE.CylinderGeometry(.08,.12,.45,10),new THREE.MeshStandardMaterial({color:0x777777,metalness:.7}));exhaust.rotation.x=Math.PI/2;exhaust.position.set(.75,.48,2.1);g.add(exhaust);g.position.set(x,0,z);this.game.scene.add(g);const v={name,mesh:g,speed:0,maxSpeed,baseMaxSpeed:maxSpeed,accel:10,baseAccel:10,grip:.92,baseGrip:.92,steer:.9,engine:1,health:100,fuel:100,wheels,wheelStyle:'stock',lights,damageLevel:0,engineLevel:0,tireLevel:0,brakeLevel:0,suspensionLevel:0};this.vehicles.push(v);return v;}
  loadUpgrades(){const upgrades=this.game.state.get().garage?.upgrades||{};for(const v of this.vehicles){const u=upgrades[v.name];if(!u)continue;const colors={red:0xc52d2d,blue:0x2457a6,black:0x15191d,white:0xe9ecef,gold:0xd5a928};v.paint=u.paint||'red';v.mesh.children[0].material.color.setHex(colors[v.paint]??colors.red);v.wheelStyle=u.wheels||'stock';this.setWheelStyle(v,v.wheelStyle);v.tireLevel=u.tires||0;v.engineLevel=u.engine||0;v.brakeLevel=u.brakes||0;v.suspensionLevel=u.suspension||0;v.grip=Math.min(.99,v.baseGrip+v.tireLevel*.035);v.maxSpeed=v.baseMaxSpeed+v.engineLevel*4;v.accel=v.baseAccel+v.engineLevel*1.5;v.brakePower=1+v.brakeLevel*.15;v.steer=.9+v.suspensionLevel*.04;}}
  setWheelStyle(v,style){const scale=style==='sport'?1.08:style==='offroad'?1.16:1;v.wheels.forEach(w=>{w.scale.set(scale,style==='sport'?1.25:1,scale);w.material.color.setHex(style==='offroad'?0x202020:style==='sport'?0x343434:0x111111);});}
  isOwned(v){return !this.game.vehicleOwnership||this.game.vehicleOwnership.isOwned(this.game.vehicleOwnership.find(v.name));}
  selectVehicle(name){const v=this.vehicles.find(x=>x.name===name);if(!v||!this.isOwned(v))return false;this.active=v;this.game.state.update({garage:{...(this.game.state.get().garage||{}),active:v.name}});this.game.events.emit('vehicle:changed',v);return true;}
  applyDamageVisual(v){const ratio=1-v.health/100;v.damageLevel=ratio;const body=v.mesh.children[0];body.scale.y=1-ratio*.06;body.material.roughness=Math.min(.9,.28+ratio*.55);v.mesh.rotation.z=Math.sin(ratio*8)*ratio*.018;}
  enterNearest(){const p=this.game.player;let best=null,dist=Infinity;for(const v of this.vehicles){if(!this.isOwned(v))continue;const d=p.position.distanceTo(v.mesh.position);if(d<dist){dist=d;best=v;}}if(best&&dist<4){this.active=this.active===best?null:best;this.game.events.emit('vehicle:changed',this.active);}}
  update(dt){if(this.keys.has('e')&&!this.eHeld){this.eHeld=true;this.enterNearest();}if(!this.keys.has('e'))this.eHeld=false;if(!this.active)return;const v=this.active,forward=this.keys.has('w')||this.keys.has('arrowup'),reverse=this.keys.has('s')||this.keys.has('arrowdown'),left=this.keys.has('a')||this.keys.has('arrowleft'),right=this.keys.has('d')||this.keys.has('arrowright');const input=(forward?1:0)-(reverse?1:0);const traction=forward||reverse?v.engine:0.35;v.speed+=input*v.accel*traction*dt;v.speed*=Math.pow(v.grip,dt);v.speed=THREE.MathUtils.clamp(v.speed,-v.maxSpeed*.4,v.maxSpeed);const steer=(left?1:0)-(right?1:0);v.currentSteer=steer;v.mesh.rotation.y+=steer*dt*(v.steer+Math.abs(v.speed)*.035);const dir=new THREE.Vector3(0,0,-1).applyQuaternion(v.mesh.quaternion);v.mesh.position.addScaledVector(dir,v.speed*dt);v.mesh.position.x=THREE.MathUtils.clamp(v.mesh.position.x,-110,110);v.mesh.position.z=THREE.MathUtils.clamp(v.mesh.position.z,-110,110);this.game.player.position.lerp(v.mesh.position.clone().add(new THREE.Vector3(0,1.1,0)),.35);v.fuel=Math.max(0,v.fuel-Math.abs(v.speed)*dt*.003);if(v.fuel<=0)v.speed*=.92;v.health=Math.max(0,v.health-Math.abs(v.speed)*dt*.00015);v.engine=THREE.MathUtils.clamp(v.health/100,.25,1);this.applyDamageVisual(v);const braking=reverse&&v.speed>0;if(v.brakeLevel&&braking)v.speed*=Math.pow(.985+v.brakeLevel*.004,dt*60);this.game.events.emit('vehicle:speed',{speed:Math.abs(v.speed)*3.6,health:v.health,fuel:v.fuel});}
}
