const PROFILES={'Kigali Runner':{action:'route-surge',road:1.05},'Moto Taxi':{action:'traffic-thread',traffic:1.45,opportunity:1.2},'Market Hauler':{action:'cargo-drop',cargo:3,economy:1.25},'KGL E-Moto':{action:'silent-scan',traffic:1.6,opportunity:1.4,noise:.35},'Rebero Rally':{action:'hill-launch',hill:1.55},'Hill Buggy':{action:'terrain-lock',hill:2.2,terrain:2},'Mount Kigali GT':{action:'velocity-burst',speed:1.18},'Kigali Safari 4x4':{action:'recovery-pull',terrain:2.4,hill:1.9,weather:1.8,recovery:1.5},'Skyline Coupe':{action:'velocity-burst',speed:1.32,heat:1.4},'Kigali VIP':{action:'city-pass',social:1.55,economy:1.35},'Night Runner X':{action:'night-scan',night:2.4,social:1.9,opportunity:1.7}};
const EQUIP={'terrain-kit':{terrain:1.4,hill:1.35},'city-scanner':{opportunity:1.35,traffic:1.15},'smart-dash':{night:1.3,social:1.2},'rapid-repair':{recovery:1.4},'signal-beacon':{social:1.3},'weather-node':{weather:1.35},'drone-scout':{exploration:1.5},'mobile-workshop':{recovery:1.2,cargo:1.15}};
export class VehicleAbility2System{
 constructor(game){this.game=game;this.cooldown=0;this.activeAction=null;}
 active(){return this.game.vehicles?.active;}
 profile(){return PROFILES[this.active()?.name]||{};}
 mult(key){let m=this.profile()[key]||1;for(const id of this.game.equipment?.active||[]){const e=EQUIP[id];if(e)m*=e[key]||1;}return m;}
 isNight(){const t=this.game.state.get().world?.time||0;return t>=1140||t<360;}
 trigger(){const v=this.active();if(!v||this.cooldown>0)return false;const p=this.profile();const action=p.action||'route-surge';if(action==='night-scan'&&!this.isNight())return false;this.cooldown=8;this.activeAction=action;const payload={vehicle:v.name,action,terrain:this.mult('terrain'),traffic:this.mult('traffic'),opportunity:this.mult('opportunity'),social:this.mult('social')};if(action==='silent-scan'&&this.game.equipment?.has('city-scanner'))payload.scan='CITY SCANNER';if(action==='recovery-pull'){v.damage=Math.max(0,(v.damage||0)-35);payload.repaired=true;}if(action==='cargo-drop')payload.capacity=this.cargoCapacity();if(action==='velocity-burst')payload.speedBoost=1.35;if(action==='terrain-lock')payload.grip=this.mult('terrain')*1.5;if(action==='hill-launch')payload.hillGrip=this.mult('hill')*1.4;this.game.state.update({vehicleAbility:{...payload,lastAction:Date.now()}});this.game.events.emit('vehicle:ability-active',payload);return true;}
 update(dt){this.cooldown=Math.max(0,this.cooldown-dt);const v=this.active();if(!v)return;const el=document.querySelector('#vehicle-ability');if(el)el.textContent=`ABILITY 3.0: ${v.name} · ${this.profile().action?.toUpperCase()||'ROUTE-SURGE'}${this.cooldown>0?` · ${this.cooldown.toFixed(1)}s`:' · READY'}`;if(this.activeAction==='velocity-burst'&&this.cooldown>7)v.speed=Math.min((v.speed||0)*1.01,Number(v.maxSpeed||40));if(this.activeAction==='terrain-lock')v.gripBoost=1.5;}
 cargoCapacity(){return Math.max(1,Math.round(this.mult('cargo')));}
 terrainAccess(){return this.mult('terrain')>1.35||this.mult('hill')>1.35;}
 trafficFlow(){return this.mult('traffic')>1.2;}
}
